--- #YAML:1.0
name:                HTML-Packer
version:             0.4
abstract:            Another HTML code cleaner
license:             perl
author:              
    - Merten Falk <nevesenin@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
